In [ ]:
import numpy as np
k = np.ones((2,3),complex)
print(k)

In [18]:
my_arr4 = np.array([[1, 2, 3], [4, 5, 6]])
l = np.ones_like(my_arr4,complex)
print(l)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [30]:
x = np.array([0,0.5,1,1.5])
print(x)

x = np.arange(0,7,1,dtype=complex)
print(x)

[0.  0.5 1.  1.5]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [58]:
#creating vectors with zeros and ones
x = np.zeros((4,2))
print(x)
#doing operations on above progran
x[0] = 4.5
x[2] = 2
print(x[0::2])

import numpy.random as r
#creating 3d arrays
d3 = r.rand(3,3,3)
print(d3)
print(x[0,:])
dimension = np.ndim(d3)
shape = np.shape(d3)
print(f"{dimension} {shape}")

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[4.5 4.5]
 [2.  2. ]]
[[[0.5067488  0.61641171 0.21056896]
  [0.57548781 0.28713664 0.71746389]
  [0.04710991 0.18188183 0.9454617 ]]

 [[0.24980333 0.7375034  0.04129954]
  [0.37883184 0.85011892 0.72890684]
  [0.28460787 0.38599838 0.13127125]]

 [[0.22625047 0.17804974 0.16700977]
  [0.43240559 0.60316966 0.27213068]
  [0.39031325 0.7473016  0.74223982]]]
[4.5 4.5]
3 (3, 3, 3)
