In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv('ecommerce_customer_data.csv')
X = data.select_dtypes(include=np.number).drop(columns=['Churn'])
y = data['Churn']

In [4]:
print(data['Churn'].value_counts())

Churn
0    1379
1     621
Name: count, dtype: int64


In [5]:
X_train,X_test,y_train,y_test = train_test_split(
    X  ,  y,  test_size = 0.2,  random_state = 45
)

In [6]:
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.fit_transform(X_test)

In [7]:
def performance(model_obj,msg = ' '):
    if msg == 'svc' or 'knn':
        model_obj.fit(X_train_scaler,y_train)
        y_pred = model_obj.predict(X_test_scaler)
    else :
        model_obj.fit(X_train,y_train)
        y_pred = model_obj.predict(X_test)

    print(set(y_pred))
    print('Classification Report : \n',classification_report(y_test,y_pred))
    print('Confusion Matrix : \n',confusion_matrix(y_test,y_pred))    
    print('Accuracy score : \n',accuracy_score(y_test,y_pred))

In [8]:
dt = DecisionTreeClassifier()
performance(model_obj=dt,msg = 'DecisionTree')

{np.int64(0), np.int64(1)}
Classification Report : 
               precision    recall  f1-score   support

           0       0.68      0.68      0.68       267
           1       0.36      0.37      0.37       133

    accuracy                           0.57       400
   macro avg       0.52      0.52      0.52       400
weighted avg       0.58      0.57      0.58       400

Confusion Matrix : 
 [[181  86]
 [ 84  49]]
Accuracy score : 
 0.575


In [9]:
dt = DecisionTreeClassifier(class_weight = 'balanced')
performance(model_obj=dt,msg = 'DecisionTree')

{np.int64(0), np.int64(1)}
Classification Report : 
               precision    recall  f1-score   support

           0       0.68      0.72      0.70       267
           1       0.36      0.32      0.34       133

    accuracy                           0.58       400
   macro avg       0.52      0.52      0.52       400
weighted avg       0.57      0.58      0.58       400

Confusion Matrix : 
 [[192  75]
 [ 91  42]]
Accuracy score : 
 0.585


In [10]:
knn = KNeighborsClassifier()
performance(knn,msg = 'knn')

{np.int64(0), np.int64(1)}
Classification Report : 
               precision    recall  f1-score   support

           0       0.65      0.81      0.72       267
           1       0.26      0.14      0.18       133

    accuracy                           0.59       400
   macro avg       0.46      0.47      0.45       400
weighted avg       0.52      0.59      0.54       400

Confusion Matrix : 
 [[217  50]
 [115  18]]
Accuracy score : 
 0.5875


In [8]:
knn = KNeighborsClassifier(n_neighbors=7)
performance(knn,msg = 'knn')

{np.int64(0), np.int64(1)}
Classification Report : 
               precision    recall  f1-score   support

           0       0.67      0.86      0.75       267
           1       0.32      0.14      0.19       133

    accuracy                           0.62       400
   macro avg       0.49      0.50      0.47       400
weighted avg       0.55      0.62      0.56       400

Confusion Matrix : 
 [[229  38]
 [115  18]]
R2 score : 
 -0.7234096477147929
Accuracy score : 
 0.6175


In [9]:
svc = SVC(kernel='rbf',
    C=5,
    gamma='scale',
    class_weight='balanced'
)
performance(svc,msg = 'svc')

{np.int64(0), np.int64(1)}
Classification Report : 
               precision    recall  f1-score   support

           0       0.64      0.52      0.57       267
           1       0.30      0.41      0.34       133

    accuracy                           0.48       400
   macro avg       0.47      0.46      0.46       400
weighted avg       0.52      0.48      0.49       400

Confusion Matrix : 
 [[138 129]
 [ 79  54]]
R2 score : 
 -1.3429359916645551
Accuracy score : 
 0.48
